* ten-hundred-mode

A thing to help people use only the ten hundred most usual English words.

Copyright 2016 Aaron Miller <me@aaron-miller.me>

Last revision: Friday, April 8, 2016, ca. 18:00.

This program is free software; you can redistribute it and/or
modify it under the terms of the GNU General Public License as
published by the Free Software Foundation; either version 2 of
the License, or (at your option) any later version.

This program is distributed in the hope that it will be
useful, but WITHOUT ANY WARRANTY; without even the implied
warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the GNU General Public License for more details.

You should have received a copy of the GNU General Public
License along with this program; if not, write to the Free
Software Foundation, Inc., 59 Temple Place, Suite 330, Boston,
MA 02111-1307 USA

* Commentary:

Lately there has been some interest in writing with only the ten
hundred most used English words. Even the news has talked about one
thing that makes your computer take away words that aren't in the
ten hundred most used.

(Mostly the news talked about that thing because the person who
wrote it did so in part to make a point about someone called Donald
Trump, not because the thing was interesting in its own right. But
that's okay, because the people who write the news need something
to do all day just like everyone else.)

Someone on Hacker News asked if there was a thing like that for
Emacs. There is, sort of, but it's old and not easy to find, and it
doesn't work very well. So I thought I'd write a new one that
everyone can find and use. This is that thing.

It knows the ten hundred most used words, and when you type a word,
it checks to see if your word is one of them. If not, the computer
takes away the word you typed, and suggests some words like the one
it took away but which are okay to use. (This last part can be a
little slow, and it isn't always very helpful, so you can turn it
off if you want.) Words that start with a big letter, like names,
don't get taken away, even if they would be normally.

This thing doesn't know very much. If you aren't typing normally,
it probably will let you get away with using words you aren't
supposed to use. That's not nice, though, so don't do that.

* Contributing:

If you think of a way this thing can do a better job of taking away
words that aren't okay to use, let me know, or (even better) add it
to the thing and then let me know.

I hope you like it!
